In [8]:
# Create a reference to the CSV and import it into a Pandas DataFrame
import pandas as pd
csv_path = "Resources/EclipseBugs.csv"
pd.read_csv(csv_path)
eclipse_df = pd.read_csv(csv_path)
eclipse_df.head()

,Bug ID,Product,Component,Assignee,Status,Resolution,Summary,Changed,Assignee Real Name,Classification,...,Number of Comments,Opened,OS,Priority,Reporter,Reporter Real Name,Severity,Target Milestone,Version,Votes
0,3638,JDT,UI,aeschli,VERIFIED,FIXED,Package Viewer: order resource folders before ...,1/17/2002 7:28,Martin Aeschlimann,Eclipse,...,3,10/10/2001 22:58,Windows NT,P1,aeschli,Martin Aeschlimann,major,---,2,0
1,3854,JDT,UI,aeschli,VERIFIED,FIXED,Wrong execution's classpath. (1GEY0W0),1/18/2002 4:02,Martin Aeschlimann,Eclipse,...,5,10/10/2001 23:01,Windows NT,P1,david_audel,David Audel,normal,---,2,0
2,4188,JDT,UI,aeschli,VERIFIED,FIXED,type hierachy - typo (1GJW2XJ),1/28/2002 3:12,Martin Aeschlimann,Eclipse,...,3,10/10/2001 23:07,Windows 2000,P1,erich_gamma,Erich Gamma,normal,---,2,0
3,5115,JDT,Debug,aeschli,VERIFIED,FIXED,Workspace source locator fails with mulitple p...,11/13/2001 10:11,Martin Aeschlimann,Eclipse,...,10,10/19/2001 13:41,Windows 2000,P1,darin.eclipse,Darin Wright,normal,---,2,0
4,5820,JDT,UI,aeschli,VERIFIED,FIXED,Close all editors brings up hierarchy of object,11/20/2001 16:22,Martin Aeschlimann,Eclipse,...,5,11/12/2001 18:18,Windows 2000,P1,jed.anderson,Jed Anderson,normal,---,2,0

In [9]:
# Finding the average number of comments per bug

average_comments = eclipse_df["Number of\nComments"].mean()
average_comments

8.75

In [10]:
# Grouping the DataFrame by "Assignee"
assignee_group = eclipse_df.groupby("Assignee")

# Count how many of each component Assignees worked on and create DataFrame
assignee_work = pd.DataFrame(assignee_group["Component"].value_counts())
assignee_work.head()

                                Component
Assignee       Component
Aaron_Ferguson UI                      10
Adam_Schlegel  UI                       7
ChrisAustin    User Assistance          3
Claude_Knaus   UI                      31
               Text                     7

In [18]:
# Rename the "Component" column to "Component Bug Count"

                                 0
Assignee       Component
Aaron_Ferguson UI               10
Adam_Schlegel  UI                7
ChrisAustin    User Assistance   3
Claude_Knaus   UI               31
               Text              7

In [12]:
# Find the percentage of bugs overall fixed by each Assignee
total_bugs = assignee_group["Assignee"].count()
bugs_per_user = assignee_group["Assignee"].value_counts()

user_bug_percent = pd.DataFrame((bugs_per_user/total_bugs)*100)
user_bug_percent.head()

                               Assignee
Assignee       Assignee
Aaron_Ferguson Aaron_Ferguson     100.0
Adam_Schlegel  Adam_Schlegel      100.0
ChrisAustin    ChrisAustin        100.0
Claude_Knaus   Claude_Knaus       100.0
Curtis_Windatt Curtis_Windatt     100.0

In [19]:
# Merge the "Percent of Total Bugs Assigned" into the DataFrame
assignee_work = assignee_work.merge(user_bug_percent, on="Assignee")

# Remove the extra columns
assignee_work = assignee_work[[
    "Assignee", "Percent of Total Bugs", "Component", "Component Bug Count"]]
assignee_work.head()

C:\Users\Tai\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 'Assignee' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version

ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat